version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/mattszeinweb
    restart: always
    ports:
      - 3000:3000
    command: npm run dev
